// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0FMneYbMPeDTF-niBdWrWhKhFa2J2xo8',
    appId: '1:737338530003:web:2f9a6358ded5079cca9c26',
    messagingSenderId: '737338530003',
    projectId: 'test-database-601c6',
    authDomain: 'test-database-601c6.firebaseapp.com',
    databaseURL: 'https://test-database-601c6-default-rtdb.firebaseio.com',
    storageBucket: 'test-database-601c6.appspot.com',
    measurementId: 'G-W6QNZ30JKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUV_XMirq34RnvBvZSD5UHVC2uGiTc7As',
    appId: '1:737338530003:android:336ad911e875bb40ca9c26',
    messagingSenderId: '737338530003',
    projectId: 'test-database-601c6',
    databaseURL: 'https://test-database-601c6-default-rtdb.firebaseio.com',
    storageBucket: 'test-database-601c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFeW-0kQaVJul0fqbm7SWm7c9puuypKP4',
    appId: '1:737338530003:ios:72c412e46ada05c0ca9c26',
    messagingSenderId: '737338530003',
    projectId: 'test-database-601c6',
    databaseURL: 'https://test-database-601c6-default-rtdb.firebaseio.com',
    storageBucket: 'test-database-601c6.appspot.com',
    iosClientId: '737338530003-7n1mef6rp04if02u5mgnmm9o48jvrdr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.signInScreen',
  );
}
